version: '3.8'
services:
  product-service:
    image: csag095/product-service:${BUILD_NUMBER} 
    restart: always
    environment:
      - DATABASE_URL=jdbc:mysql://mysql-db:3306/service_db
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
    ports:
      - "8081:8080"  
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: service_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"

