apiVersion: v1
kind: Service
metadata:
  name: my-sql-server
  labels:
    app: my-sql-server
spec:
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None  #makes it a headless service
  selector:
    app: my-sql-server
